Update registry.json
kyb3r/modmail pull request #2864
Opened 2020-10-25 03:56 UTC by lorenzo132

add media-only plugin, 4jr's plugin edited

2020-10-25 14:49 UTC, fourjr requested changes
PR is framed in a way such that it says that it only allows images in channels. However, code also does other things such as adding reactions. Misleading description.

In addition, there is no way to set the `config['emojis']` and the bot will probably error out?

2020-10-25 15:04 UTC, lorenzo132 commented
Hey, i'v removed the emoji functionality's to make sure it will not bug out

2020-10-28 08:29 UTC, fourjr approved these changes

2020-10-28 08:33 UTC, fourjr commented
Merged. [https://github.com/kyb3r/modmail/commit/7da970c17666b26149fbda4586fa5a79ec8b2c99]

2020-10-28 08:33 UTC, closed without merging