Added `thread_auto_open_silently`
kyb3r/modmail pull request #2887
Opened 2020-11-15 15:21 UTC by zoemartin01

I just added `thread_auto_open_silently` with the default value 'false' as this allows for the users customisation on a recently changed feature.

2020-11-16 09:30 UTC, DAzVise commented
You forgot to add the config in `core/config_help.json`

2020-11-18 12:59 UTC, fourjr commented on core/config_help.json
> +    "description": "Setting this configuration will open a new thread silently by default.",
```suggestion
    "description": "Setting this configuration will always open a new thread silently in contact.",
```

2020-11-18 13:00 UTC, fourjr requested changes
Config variable should be changed to `thread_contact_silent` as it only affects contact

2020-11-18 13:00 UTC, fourjr commented on core/config.py
> +        "thread_creation_silent": False,
it has to be added to `booleans` too

2020-11-19 15:03 UTC, fourjr commented
Thanks for the contributions! This PR has been merged in https://github.com/kyb3r/modmail/commit/a123bf617603abb9a1f32f74832595d2d508372b, not sure why the PR wasn't autoclosed.

2020-11-19 15:03 UTC, closed without merging