Change Max Channel per Category to 49
kyb3r/modmail pull request #3003
Opened 2021-04-19 02:27 UTC by Coolguy3289

Addresses https://github.com/kyb3r/modmail/issues/3002
Will add a 1 channel buffer to the check to account for Discord API bugs preventing the category from actually reaching 50 channels.

2021-04-19 13:33 UTC, Jerrie-Aries requested changes

2021-04-19 13:33 UTC, Jerrie-Aries commented on core/thread.py
> +        if category is None and len(cat.channels) == 49:
```suggestion
        if category is None and len(cat.channels) >= 49:
```

2021-04-22 12:41 UTC, Jerrie-Aries commented
Tbh, this PR is not complete yet. I think you need to edit the `if` statement for `fallback` category as well.
In `thread.py` line 1212:
```
                if fallback and len(fallback.channels) <= 49:
```

And also about the solution, since it's the glitch/lag on discord side, I'm unsure whether it should be handled in the code here, or in the `exception` when creating the thread.
So, let the devs look at this first.

2021-04-25 13:24 UTC, fourjr commented
This PR has been manually merged.  Thanks for the contribution.

2021-04-25 13:24 UTC, closed without merging