Re-Add/Expand on FourJR Plugins
kyb3r/modmail pull request #3211
Opened 2022-10-01 03:06 UTC by Coolguy3289

2022-10-01 03:06 UTC, Coolguy3289 commented
Awaiting merge of PR on FourJR's branch before marking ready for review.

2022-10-01 06:47 UTC, Jerrie-Aries requested changes

2022-10-01 06:47 UTC, Jerrie-Aries commented on plugins/registry.json
> +    },
```suggestion
    },
```

Duplicate :)

2022-10-02 01:48 UTC, fourjr requested changes
`bot_version` has to be set to `4.0.0` and branch should be `v4`.

2022-10-03 14:09 UTC, Coolguy3289 commented
Requested changes implemented.

2022-10-18 00:41 UTC, fourjr approved these changes

2022-10-18 00:41 UTC, merged