Alias add improvements
kyb3r/modmail pull request #3343
Opened 2024-06-09 10:56 UTC by martinbndr

- Fixes an issue with error message being incorrect.
- Protects eval command for being added into an alias if the user does not have permissions to it as Owner level etc. as the command is quite dangerous and should not be added by normal moderators (Could be used to nuke server for example).

2025-12-05 21:29 UTC, StephenDaDev approved these changes, later dismissed
Looks good.

2025-12-13 22:57 UTC, sebkuip requested changes
There's an issue that you forgot to check causing errors.

2025-12-13 22:57 UTC, sebkuip commented on cogs/utility.py
This call to make_alias does not have the new ctx arg which would break editing aliases

2025-12-13 23:52 UTC, martinbndr commented
> There's an issue that you forgot to check causing errors.

Ih damn yea seems I forgot that, will fix it in next few days when I have time.

2025-12-19 13:54 UTC, martinbndr commented
Moved this to #3422. The reviewed issue has been implemented there. Closing this now

2025-12-19 13:54 UTC, closed without merging